OWASP/www-project-secure-headers

tab_technical.md

The link to Mozilla Observatory points to a staging site rather than the live production site. Fixes the site link to the production site and adds two GitHub repository links for the scanner and website repositories that support it. Fixes mozilla/http-observatory-website#224.

Repair link to Mozilla Observatory

---

tab_headers.md

On my last PR I didn't let clear enough that those headers were deprecated, so I added a ⚠️ to them.

improved deprecation warnings visilibity

---

.github/workflows/check-external-links.yml
index.md
tab_compatibility.md
tab_headers.md
tab_technical.md

Hi,
This PR is related to this [discussion](https://github.com/OWASP/www-project-secure-headers/issues/15#issuecomment-782067673).
Precisely it:
* Fix dead links.
* Try the `<url>` syntax in order to tackle not clickable links once converted by jekyll.

Handle dead and not clickable links

---

tab_technical.md

This PR remove the site https://cyh.herokuapp.com/cyh  based on this [discussion](https://github.com/OWASP/www-project-secure-headers/pull/25#issuecomment-785880629).

Remove broken sites

---

tab_compatibility.md

This PR add missing information in the compatibility table.
I have the following proposal for the table:
_I think that, in terms of maintenance and info accuracy, it can be better to replace the table by permalinks to https://caniuse.com site for every headers when available and other site provding the information otherwise. Using this way, the reader will have all the details about the comptibility info and optionally associated notes._
If you are OK with the proposal, so, say it to me and I will do the update in this PR.

Complete missing entries.

---

tab_bestpractices.md
tab_top.md

Hi,
This PR add a new tab for containing the [Best Practices](https://wiki.owasp.org/index.php/OWASP_Secure_Headers_Project#tab=Best_Practices) section. It refer to [this discussion](https://github.com/OWASP/www-project-secure-headers/pull/32#issuecomment-791407051)
It is a start content and can be completed with a recommanded config for the active headrers (like it was done on the wiki).
Thank in advance 😃

Add new tab for best practices.

---

_config.yml

README.md doesn't need to be deployed to owasp.org/www-project-secure-headers/README.md

Don't deploy README.md

---

.github/workflows/check-external-links.yml
markdown-link-check_config.json
tab_misc.md

Hi,
This PR add a new *misc* tab providing extra information about HTTP security headers in general. 
The OSHP is focused on HTTP Security **Response** headers but some **Request** header like `Sec-Fetch-*` ([source](https://developer.mozilla.org/en-US/docs/Glossary/Fetch_metadata_request_header)) can be useful to know from a defensive point of view.
I have proposed a new dedicated tab in order to not distrub the global content stucture and cause any confusion on the reader side.

Add a new tab with extra info.

---

tab_casestudies.md
tab_technical.md

Hi,
This PR add a new tab listing company/software referencing the project in their documentation/website.
Google dork used to find more ref: 
`link:owasp.org/www-project-secure-headers/` 

Add case studies tab

---

.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/issue_form.yml

Hi,
This PR add a template for new issues opened on the project content, this, using new GH feature.
Sources:
- https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository
- https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms
Thank you very much in advance 😃

Add issue template using GH new feature

---

tab_headers.md

Hi,
This PR moved the [Expect-CT](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Expect-CT) header to the **deprecated** section because it is obsolete since June 2021:
Thank you very much in advance 😃

Mark Expect-CT header as deprecated

---

index.md

Hi,
This PR add a section on the main tab to provide information about channel used for communication:
* GitHub [discussions](https://github.com/OWASP/www-project-secure-headers/discussions) area.
* Dedicated [Google group](https://groups.google.com/a/owasp.org/g/secure-headers-project).
Thank in advance 😃

Add information about channel used for communication

---

tab_bestpractices.md

Hi,
This PR add a section providing hints to prevent exposure to cross-site scripting when hosting uploaded files and opening them in the same web browsing context than the application.
The section introduce usage of the HTTP response header named [Content-Disposition](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Disposition).
I added content into the **Best Practices** tab and not the **Response Headers** tab because this is a specific use case.
Thanks a lot in advance 😃

Prevent exposure to XSS when hosting uploaded files

---

.github/ISSUE_TEMPLATE/issue_form.yml
index.md

Hi,
This PR update the location that we use to manage the discussions as well as the roadmap follow-up.
I updated the issue template to instruct users to create the issue on the new repo:
@riramar  Can you disable the **Discussions** feature on this repo because now we will use the **Discussions** of [this project](https://github.com/oshp/oshp-tracking/discussions) on the OSHP org.

Update location info

---

README.md
tab_compatibility.md
tab_headers.md

This PR add a temporary work round for the [adobe link validation problem](https://github.com/oshp/oshp-tracking/issues/8) and update badge in missed location.

Add temporary work around for adobe link

---

tab_bestpractices.md

Let me know if I should complete remove the mentioning of the gist, or if we should add the actual git clone commands?

Bestpractice: mention OSHP Validator

---

tab_technical.md

Hi,
This PR performs the following changes in the **Technical** tab:
* Add the Google [CSP Evaluator Core Library](https://github.com/google/csp-evaluator) to the list into the **Analysis Tools** section.
* Add a code snippet using the Google [CSP Evaluator Core Library](https://github.com/google/csp-evaluator) into the **Miscellaneous Hints** section.
* Remove dead links and not maintained project:

Add CSP Evaluator Core Library and cleanup

---

tab_bestpractices.md

Since default-src is 'self', it seems that child-src 'self' is redundant.

Remove child-src from Content-Security-Policy

---

.github/workflows/monitoring-technical-references-generate-dashboard.yml
README.md
_config.yml
ci/headers_add.json
ci/headers_remove.json
ci/monitoring_technical_references_generate_dashboard.py
index.md
monitoring_technical_references_dashboard.md
tab_technical.md

Hi,
This PR add the automated generation of a monitoring dashboard for referenced GitHub projects in the tab named **Technical** each time the file **tab_technical.md** is modified.
The goal is to allow detection of old and dead projects.
It also add information about the reference JSON files added few weeks ago to the project.

Add monitoring dashboard for referenced GitHub projects in the tab named Technical

---

README.md
index.md
info.md

Hi,
This PR update the project status badge to the reference one specified below:
- https://github.com/OWASP/www-committee-project/blob/master/tab_resources.md
- https://owasp.org/www-committee-project/#div-resources

Update badge with reference url

---

tab_casestudies.md

Hi,
This PR add new company referencing OSHP.
I used this dork: `allintext:"OWASP Secure Headers Project" -site:owasp.org -site:github.com -site:youtube.com -site:twitter.com -site:linkedin.com`.
Some company are using the old link pointing to the wiki that is correctly redirected to the new site.

New company referencing OSHP

---

index.md
tab_casestudies.md
tab_codesnippets.md
tab_technical.md

Hi,
This PR performs the following updates:
* I removed the REST API line for the explanation specified [here](https://github.com/oshp/oshp-tracking/discussions/6#discussioncomment-4620641):
* I added a sub menu to allow to directly reach a wanted language section for the libraries:
* I moved the code snippets into a dedicated tab:

Remove REST API line and rearrange content

---

tab_bestpractices.md

Work on this topic: https://github.com/OWASP/common-requirement-enumeration/issues/251
Due to the way in which the HTML is rendered, I must use HTML comment to add the `<div>` for OpenCRE ref:
So it's a second try...

Work on integration with OpenCRE OWASP project

---

tab_casestudies.md

This PR add info about how to make a reference link to OSHP site targeting a specific tab.

Add info about cross-ref

---

index.md

Hi,
New round for **Point C** of https://github.com/oshp/oshp-tracking/issues/16 😃  
Based on the result of the previous PR, I fixed the location of the CSS to its correct relative path on the OSHP website:

Try to fix table rendering issue - round 3

---

assets/js/direct-link-handler.js
index.md

Hi,
This PR add a custom JS script that is a tentative to allow to direct link a section (header) into a tab (div).
I based it after analyzing the OWASP site template naming convention.
I tested the script locally on Chrome (last release) but to finally validate the idea or not, I need to live usage...

Try to add a direct section linker.

---

tab_codesnippets.md

Hi,
The site [securityheaders.com](https://securityheaders.com) does not return the grade as header because, now, [the API require a subscription](https://securityheaders.com/api/).
I updated the procedure to leverage the HTML content to continue to use the service in free and automated way:

Update procedure to use securityheaders.com

---

README.md
index.md
tab_headers.md

Hi,
This PR add the following note about the behavior of the STS over an HTTP connection:
🌎 Source: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Strict-Transport-Security#description

Add note about STS

---

tab_bestpractices.md

Hi,
This PR add the [form-action](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/form-action) directive to the CSP proposed because, as this directive does not default to *default-src*, it can be used to bypass a CSP:
Tool: https://csp-evaluator.withgoogle.com/

Add form-action

---

tab_bestpractices.md

Hi,
This PR add the headers disclosing the presence of the [Next.js](https://nextjs.org/) web framework.
The PR handle this issue: https://github.com/oshp/oshp-tracking/issues/20

Add Next.js headers  to remove

---

tab_bestpractices.md

Hi,
This PR add a collection of HTTP response headers disclosing the presence of the [Dynatrace](https://www.dynatrace.com/) platforms.
🌎 [Source](https://www.dynatrace.com/support/help/platform-modules/digital-experience/web-applications/initial-setup/firewall-constraints-for-rum#response-headers) used.
Thanks in advance 😉

Add dynatrace HTTP response headers.

---

tab_misc.md

Hi,
This PR add the content about the [Private Network Access](https://developer.chrome.com/blog/private-network-access-update/#what-is-private-network-access) header.
Tested on **Chrome 116 release channel** with all default settings:

Add PNA content

---

index.md
tab_casestudies.md

Hi,
This PR handle this point: https://github.com/oshp/oshp-tracking/issues/27
It also add a new company referencing the OSHP: [Ivanti](https://forums.ivanti.com/s/article/HTTP-Security-Headers-X-Frame-Options-X-XSS-Protection-X-Content-Type-Options)

Add ref to "how to" linking system in the main tab

---

tab_bestpractices.md

Thank you very much for recommending my CORS library, [jub0bs/fcors](https://github.com/jub0bs/fcors).
I have since released its successor: [jub0bs/cors](https://github.com/jub0bs/cors). This PR reflects that.

Recommend jub0bs/fcors's successor library: jub0bs/cors

---

tab_headers.md

* CSP sounded too promising and easy going to me. Also the frame-ancestor option is worth to mention explicitly
* HSTS was amended using the term browser right in the beginning and added max-age in the description. 
For the term browser: maybe we should mention some place else that this tab is for browsers only. I've seen folks believing that e.g. non-browser API clients honor HSTS instead of switching off clear text HTTP on the server side.

sharpen the description for HSTS and CSP

---

tab_headers.md

Hi,
This PR add the suggestion proposed by @drwetter in PR #197 

Add note about user agent.

---

tab_bestpractices.md

Hi,
This PR add the case of "CSP bypass" via the [base-uri](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/base-uri) missing directive. 

Add info about base-uri

---

tab_bestpractices.md

Hi,
This PR add a warning based on the following discovery:
* https://bsky.app/profile/chrismckee.bsky.social/post/3lfq6yoxp3k2n
* https://www.linkedin.com/posts/righettod_appsec-appsecurity-csp-activity-7286671456380334081-qVZ4

Add warning for CSP and Web API.

---

README.md
index.md

Hi,
This PR perform minor update to ref the new tab to finalize #210 

Minor updates

---

README.md
tab_technical.md

Hi,
This PR:
* Add a quick shortcut to the **[Technical References Dashboard](https://github.com/OWASP/www-project-secure-headers/blob/master/monitoring_technical_references_dashboard.md)** generated.
* Remove the lib [NWebsec](https://github.com/NWebsec/NWebsec) as it has reached the limit of *no update* threshold:

Remove unmaintained lib

---

tab_misc.md

Hi,
This PR add a warning about the fact that support for the PNA feature was put on hold by Google:
See https://bsky.app/profile/jub0bs.com/post/3lpu7jg72zs2r for the context

Add warning about PNA.

---

tab_bestpractices.md

Hi,
This PR handle broken links detected by the validation GHA workflow:
https://github.com/OWASP/www-project-secure-headers/actions/runs/15949566172

Handle broken links.

---

tab_technical.md

Hi,
This PR:
* Remove a project that reached the out of update limit of 24 months [source](https://github.com/OWASP/www-project-secure-headers/blob/master/monitoring_technical_references_dashboard.md):
* Add the project [rust-helmet](https://github.com/danielkov/rust-helmet) for the Rust technology that was not yet covered.

Maintenance operations over the technical references.

---

tab_bestpractices.md

Hi,
This PR:
* Add info about the support for experimental values for the header **Clear-Site-Data**.
* Validate the supported directives for the header **Permissions-Policy** against a recent version of Chromium.

Add info for Clear-Site-Data and Permissions-Policy headers.
