tab_compatibility.md, tab_headers.md
Removed the new lines in the header and the 4 dashes after the first title
=> Chore: Fix MD Issues

index.md, tab_compatibility.md, tab_headers.md, tab_technical.md, tab_top.md
Fixes a handful of grammar issues and reformats much of the content as proper Markdown (e.g. tables and lists).
=> Fix Grammar & Formatting Issues

tab_compatibility.md, tab_headers.md
Hello,
This PR propose the adding of the header **Clear-Site-Data**.
From a security point of view, this header can be useful in a logout process, so, I think that it is interesting to propose its usage.
I have followed the format used for all other headers and mentioned explicitly all my sources.
I have also made the following POC in order to verify the usability before to propose this PR:
```php
<?php
//Local command to run example: "php -S localhost:8000"
//Get optional action: login / logout / random
$action="NA";
if (isset($_GET["a"])) {
$action=$_GET["a"];
}
switch ($action) {
//Login action fill session and local storage dummy data
case "login":
//1d duration persistant cookie
session_start(["cookie_lifetime" => 86400,]);         
$_SESSION["status"] = bin2hex(random_bytes(5)) . …
```
=> Propose the adding of the "Clear-Site-Data" response header

tab_compatibility.md, tab_headers.md
Hi,
This PR cover the issue #6 .
Thanks a lot in advance 😃
=> Add COEP / COOP / CORP headers

tab_technical.md
=> Add Venom Test Suites

.github/workflows/check-external-links.yml
Hi,
PR related to this [proposal](https://github.com/OWASP/www-project-secure-headers/issues/15#issuecomment-782073468).
Currently the check failed because there are dead links 😃 
Run example:
=> Add GH actions worflow to check external links

README.md
Add the logo in order to indicate the project level in the OWASP projects classification.
=> Add project logo with project status in OWASP projects classification.

tab_bestpractices.md
Hi,
This PR add a section proposing a configuration for the active headers in the *Best Practices" tab.
It take back your [idea](https://wiki.owasp.org/index.php/OWASP_Secure_Headers_Project#tab=Best_Practices) regarding web server configurations on the new site 👍
=> Add config proposal.

tab_bestpractices.md, tab_compatibility.md, tab_headers.md
=> Add Permissions-Policy header

.github/workflows/check-external-links.yml, markdown-link-check_config.json, tab_misc.md
Re-Add content for #39
- Add MISC tab.
- Add config file for link check in order to allow to control behavior like header, timeout and so on...
I will work aside on a sandbox to find a way to fix the **HTTP 503** issue. Once I have find a effective fix, I will do a separate dedicated PR.
My public sandbox is [here](https://github.com/righettod/sandbox/blob/main/README.md).
I propose to merge this PR to add the content if it fit your acceptance criteria.
=> Add a new tab with extra info.

README.md, markdown-link-check_config.json, tab_misc.md
Hi,
PR in ref to this [proposal](https://github.com/OWASP/www-project-secure-headers/pull/41#issuecomment-883507526).
=> Allow HTTP 503 and fix a typo.

tab_bestpractices.md, tab_compatibility.md, tab_headers.md
This PR handle the issue raised in issue #44
Result of the evaluation of the policy against the [CSP evaluator](https://csp-evaluator.withgoogle.com/):
I think that the policy proposed represent a good starting point.
I have also updated/removed dead links.
=> Fix issue raised in #44

tab_bestpractices.md, tab_compatibility.md, tab_headers.md, tab_technical.md
Hi,
This PR add information about the `Cache-Control` header and caching of resources from a security point of view.
I have also removed a dead link:
Thank a lot in advance 😃
=> Add caching section

tab_top.md
Hi,
This PR update the HTTP response of the different examples.
=> Update HTTP response for each sites

tab_technical.md
Hi,
This PR does the following changes:
- Sort development libraries by language to facilitate identification by development teams according to their need/context.
- Remove tools/libraries without any commit since 2020 because it is important to propose materials that are maintained in order to support last headers.
- Add new recent libraries when possible.
=> Refresh technical tab content

tab_bestpractices.md, tab_casestudies.md
Hi,
This PR provides a collection of HTTP response headers that is recommended to drop from any HTTP response to prevent any disclosure of technical information.
Thank you very much in advance 😃
=> Add headers to remove to prevent info disclosure

index.md
Hi,
PR to sync the communication channels with our discussions.
=> Adjust communicaton channel

index.md
Hi,
This PR add a section to introduce the stats projects added in the context of the task #61 .
=> Add section about stats project

index.md
Hi,
This PR updated the information about the migration from the old website.
=> Update the migration section

index.md
Hi,
This PR start the work on #67 regarding the following points:
- Considered "Documentation" but points to various tools in `https://github.com/oshp`. Unclear what the main aspect is meant to be.
- Project website has several informational tabs on HTTP headers but does not explain the tool found at `https://github.com/oshp/headers` at all.
=> Enhance project description

index.md, tab_technical.md
Hi,
This PR add the ref to the venom tests suite project mentioned in #69 as well as the badges.
=> Add section about the tests suite.

index.md
Hi,
This PR finalize documentation of all projects under the OSHP GitHub Organization for #67 
Thank in advance 😃
=> Finalize documentation

tab_headers.md
Hi,
This PR enhance the documentation about the X-Frame-Options header.
Thank in advance 😃
=> Enhance info about XFO

index.md, tab_headers.md, tab_technical.md
Hi,
This PR add the section, named **Presentations about the project**, in order to provides pointers to presentations talking about the OSHP.
=> add section about presentations

index.md
Hi,
This PR add the video of the project from the OWASP Spotlight playlist:
https://www.youtube.com/watch?v=N4F3VWQYU9E
=> Add owasp spotlight video

ci/headers_add.json, ci/headers_remove.json, tab_bestpractices.md, tab_headers.md
Hi,
This PR refresh infos about the [Permissions-Policy](https://github.com/w3c/webappsec-permissions-policy) header based on the feedback and concern raised on https://github.com/oshp/oshp-tracking/issues/11
=> Update infos about the Permissions-Policy header

tab_technical.md
Hi,
This PR add the elements discussed here:
https://github.com/oshp/oshp-tracking/discussions/12
=> Add section with hint for permissions-policy conversion

README.md, index.md
Hi,
This PR add reference and badge to the new content 😃 
In addition it enhance the rendering of the welcome tab.
=> Add ref to new content

ci/headers_add.json, ci/headers_remove.json, monitoring_technical_references_dashboard.md, tab_bestpractices.md, tab_casestudies.md, tab_compatibility.md, tab_headers.md, tab_misc.md, tab_technical.md, tab_top.md
Hi,
This PR add a new header to remove as well as fixing a typo in a menu name and add icons.
=> Add new headers to remove/icons/fix typos

info.md, tab_casestudies.md
Hi,
1) Add the page of **Spring Security** referencing the project:
https://docs.spring.io/spring-security/reference/features/exploits/headers.html
2) Add some icons size of the **INFO** panel.
=> Add "Spring Security"

ci/headers_add.json, ci/headers_remove.json, tab_bestpractices.md
Hi,
The PR add the header [X-Envoy-Upstream-Service-Time](https://webtechsurvey.com/response-header/x-envoy-upstream-service-time) to the list of headers to remove.
=> Add new header to remove

.github/workflows/monitoring-technical-references-generate-dashboard.yml, monitoring_technical_references_dashboard.md
Hi,
This PR fix the issue #102 
=> Add sync every week of the technical ref dashboard

info.md
Hi 
This PR add a section ref section in the right toolbar.
=> Add logo ref

tab_bestpractices.md
Hi,
This PR add the [PEGA-HOST](https://webtechsurvey.com/response-header/pega-host) header to the list of headers to remove.
Thanks in advance 😃 
Dom
=> Add PEGA-HOST header

tab_bestpractices.md
Hi,
This PR add the headers disclosing the usage of the java framework [Atmosphere](https://github.com/Atmosphere/atmosphere).
=> Add new headers to remove

markdown-link-check_config.json, tab_bestpractices.md
Hi,
This PR:
* Fix an error in the description of an header.
* Add additional accepted HTTP response code for the link check to prevent validation failure when the site is temporary down.
=> Fix error and enhance links validation

tab_bestpractices.md
Hi,
This PR add the following response headers related to [Varnish](https://varnish-cache.org):
- [X-Varnish-Backend](https://webtechsurvey.com/response-header/x-varnish-backend)
- [X-Varnish-Server](https://webtechsurvey.com/response-header/x-varnish-server)
=> Add varnish info disclosure related headers

tab_bestpractices.md, tab_casestudies.md, tab_codesnippets.md, tab_compatibility.md, tab_technical.md
Hi,
This PR handle the following point of https://github.com/oshp/oshp-tracking/issues/16 : 
* Centralize code snippets.
* Sync tab names.
=> Handle "oshp-tracking/issues/16"

tab_bestpractices.md
Work on this topic: 
https://github.com/OWASP/common-requirement-enumeration/issues/251
=> Start work on integration with OpenCRE OWASP project

tab_bestpractices.md
Hi,
This PR add additional HTTP response headers to remove regarding the following software:
- [Envoy](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_conn_man/headers).
- [Zipkin](https://zipkin.io/).
- [Knative](https://knative.dev/docs/).
=> Add more headers to remove.

.github/workflows/check-external-links.yml
Hi,
Add a schedule to check, one time a week on Sunday, the validity of all links.
=> Add weekly links validation.

tab_bestpractices.md, tab_casestudies.md
Hi,
This PR:
* Add both HTTP response headers disclosing the presence of IBM products.
* Remove a dead link.
=> Add new headers to remove.

ci/monitoring_technical_references_generate_dashboard.py, monitoring_technical_references_dashboard.md, tab_technical.md
Hi,
This PR implement the **point B** of https://github.com/oshp/oshp-tracking/issues/16
=> Refactor rendering of the technical tab

assets/css/styles.css, ci/monitoring_technical_references_generate_dashboard.py, tab_technical.md
Hi,
This PR try to fix the CSS issue mentioned in https://github.com/oshp/oshp-tracking/issues/16
I also removed this unmaintained project from the analysis tools list:
=> Try to fix table rendering issue.

index.md
Hi,
New round for **Point C** of https://github.com/oshp/oshp-tracking/issues/16 😃  
I seen the syntax below on the project template site on [this documentation](https://github.com/OWASP/owasp.github.io/blob/main/pages/site-documentation/index.md):
So I tried the same thing...
=> Try to fix table rendering issue  - round 2

tab_codesnippets.md
=> Add the cmd for the score

README.md, index.md
Hi,
This PR performed the following update:
* Update links to use the new direct linking feature.
* Add info about the new mock endpoint.
* Enhance UI in some location.
=> Update link and UI

tab_bestpractices.md, tab_codesnippets.md, tab_technical.md, tab_top.md
Hi,
This PR implements the **point D** of the ticket https://github.com/oshp/oshp-tracking/issues/16 
=> Update tabs order

tab_headers.md
Hi,
This PR add info about the `Strict-Transport-Security` [preload](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Strict-Transport-Security#preloading_strict_transport_security) directive.
=> Add info about STS preload directive.

tab_bestpractices.md, tab_codesnippets.md
Hi,
This PR moved the code snippet to add an http response header from the **Best Practices** tab to the **Code Snippets** tab.
=> Move code snippet

index.md
Hi,
This PR add the URL of the GH atom feed to be notified when a push is performed on this repo.
=> Add atom feed

README.md
Hi,
This PR just add the template of message to use for communication on social media about OSHP updates.
=> Add social media communication template

tab_bestpractices.md
Handle this [request](https://github.com/OWASP/www-project-secure-headers/pull/98#issuecomment-1656369799).
=> Handle user request

README.md
Hi,
This PR update the template used for communication in social media.
=> Update communication template

tab_bestpractices.md
Hi,
This PR add the response headers indicating the presence of the [LiteSpeed](https://litespeedtech.com/products) web server.
🌎 [source](https://docs.litespeedtech.com/lscache/devguide/controls/#response-headers).
=> Add LiteSpeed headers

tab_bestpractices.md
Hi,
🎯 This PR add the headers to remove for the following software:
* [Umbraco CMS](https://umbraco.com/products/umbraco-cms/).
* [Oracle Commerce](https://www.oracle.com/cx/ecommerce/).
🌎 **Source:** I developer a script to search for HTTP response headers disclosing information using the [majestic top site](https://blog.majestic.com/development/majestic-million-csv-daily/).
💻 **Execution overview:** 
📖 **Code:**
```python
import requests
import re
import shutil
import os
import sys
from multiprocessing import Pool
from termcolor import colored
from colorama import just_fix_windows_console
def loadOSHPHeaders():
resp = requests.get("https://owasp.org/www-project-secure-headers/ci/headers_remove.json")
return resp.json()["headers"]
def loadCommonsHeaders():
resp = …
```
=> Add headers for Umbraco CMS and Oracle Commerce.

assets/images/README.md, tab_bestpractices.md
Hi,
This PR add a new section, in the **Best Practices** tab, regarding the configuration of the CORS headers .
🤝 @riramar I need your help to review my proposal and ensure that my content is accurate, helpful and does not any technical mistake.
📋 It is a work on this [issue](https://github.com/oshp/oshp-tracking/issues/19).
Thank you a lot for your help 👍
=> Add CORS section

tab_bestpractices.md
Hi,
This PR add headers disclosing information about the Microsoft Exchange software in use.
🌎 Sources:
* https://learn.microsoft.com/en-us/openspecs/exchange_server_protocols/ms-ashttp/08ad30b6-5b73-41bc-890b-1cab2cf49827
* A assessment I performed recently against a Exchange on premise instance.
=> Add headers for Microsoft Exchange.

tab_bestpractices.md
Hi,
This PR fix this BUG:
https://github.com/oshp/oshp-validator/issues/5
Thanks 👍
=> [BUG] space character in Strict-Transport-Security

.github/CODEOWNERS, .github/pull_request_template.md
Hi,
This PR define PR user mapping and template. See [here](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners)
=> Create CODEOWNERS and PR template

.github/pull_request_template.md, tab_bestpractices.md
> [!WARNING]
> @righettod : Take a first look at the PR.
> [!IMPORTANT]
> Describe the changes performed by the PR.
Hi,
This PR:
1. Add the header disclosing the usage of the web framework [Apache Cocoon](https://cocoon.apache.org/) is used as well as the version used.
2. Update for the template used for PR to use new GH alerting format ([source](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#alerts)).
=> Add header for apache cocoon and update PR template.

tab_bestpractices.md
Hi,
This PR add a little hint about application of headers proposed.
It is based on https://github.com/oshp/oshp-tracking/discussions/25
It is part of the work on:
- https://github.com/oshp/oshp-tracking/issues/24
- https://github.com/oshp/oshp-tracking/issues/19
Thanks in advance 👍
=> Add hints for API

.github/workflows/headers-generate-json-files.yml, .github/workflows/monitoring-technical-references-generate-dashboard.yml
Hi,
This PR try to fix issue https://github.com/oshp/oshp-tracking/issues/26
=> Fix CI build error

.github/workflows/monitoring-oshp-site-references.yml, ci/monitoring_oshp_site_references.py, tab_casestudies.md
Hi,
This PR add materials to ensure that every site, mentioned in the "Case Studies" area, still mentioned the OSHP site.
I have also updated the "Case Studies" tab by removing dead links.
=> Add Case Studies monitoring materials

tab_headers.md
Hi,
This PR updated references and explanation for CORP/COEP/COOP headers.
=> CORP/COEP/COOP headers content update.

.github/workflows/check-external-links.yml, .github/workflows/headers-generate-json-files.yml, .github/workflows/monitoring-oshp-site-references.yml, .github/workflows/monitoring-technical-references-generate-dashboard.yml, markdown-link-check_config.json
Hi,
This PR update versions of GH actions used to handle warnings.
=> GHA maintenance

ci/headers_add.json, ci/headers_remove.json, tab_bestpractices.md, tab_headers.md
Hi,
PR handle the issue https://github.com/oshp/oshp-tracking/issues/28
=> Add PRAGMA header and align reco on active headers only.

ci/headers_add.json, ci/headers_remove.json, tab_bestpractices.md
=> Add missing link to the new section

ci/headers_add.json, ci/headers_remove.json, tab_bestpractices.md
Hi,
This PR add headers disclosing presence of K8S.
=> Presence of K8S.

ci/headers_add.json, ci/headers_remove.json, tab_bestpractices.md, tab_headers.md
Hi,
This PR add a ref to https://redbot.org that I found on MDN:
=> Add ref to redbot.org tool

monitoring_technical_references_dashboard.md, tab_technical.md
Hi,
This PR add the slides of the presentation I gave to the [VOXXED Luxembourg](https://luxembourg.voxxeddays.com/en/) conference yesterday.
The video will be release in coming month.
=> Add presentation about CSP.

tab_bestpractices.md
Hi,
This PR add a reco about where to set the header `Clear-Site-Data`.
I discovered this thanks to a friend that faced an loading time issue by setting the header on the welcome page of its web app 😉
=> Add note about Clear-Site-Data header

tab_bestpractices.md, tab_headers.md
Hi,
This PR update the proposed value for the `Permissions-Policy` header based on features supported by the last version of Chromium.
Linked to https://github.com/oshp/oshp-tracking/issues/24
=> Update value for the Permissions-Policy header.

markdown-link-check_config.json, tab_bestpractices.md
Hi,
This PR add a header disclosing the presence and version of the CMS [Joomla](https://www.joomla.org/).
=> Add new header

README.md, index.md, info.md, leaders.md
Hi,
This PR update the material to reflect the move to the production state.
=> Move to PROD state

tab_bestpractices.md
Hi,
This PR:
* Add a hint about the disclosure of the presence of **Spring Boot** and **Actuator** via the `Content-Type` response header.
* Remove unneeded header level.
=> Add hint about spring boot

tab_technical.md
Hi,
This PR add the [secure](https://github.com/TypeError/secure) python lib.
Ref:
=> Add new python lib.

tab_bestpractices.md
Hi,
This PR add a header disclosing the presence of [IBM WebSphere DataPower](https://www.ibm.com/products/datapower-gateway) in the call flow.
=> Add header for IBM WebSphere DataPower.

tab_headers.md
Hi,
This PR add a collection of blog posts from https://andrewlock.net/ about:
* Cross-Origin-Embedder-Policy
* Cross-Origin-Opener-Policy
* Cross-Origin-Resource-Policy
=> Add resources

README.md, index.md, info.md, tab_logo.md
Hi,
This PR fix this [ref error](https://github.com/OWASP/www-project-secure-headers/issues/204#issuecomment-2557474850).
It also update hashtag used to social network posts.
=> Fix ref error.

ci/monitoring_technical_references_generate_dashboard.py, ci/tab_stats_generate_md_file.py
Hi,
This PR just change the date emoji to a calendar.
=> Change emoji

ci/tab_stats_generate_png_files.sh
Hi,
This PR change the theme and background of the PNG image rendering because current settings used cause image color to not being visible.
=> Tune PNG rendering.

ci/tab_stats_generate_png_files.sh, ci/tab_stats_mermaid_config.json
Hi,
This PR define a **custom config file and CSS style** for the theme and background of the PNG image rendering because using simply the **forest** theme cause image color to not being visible.
I also tried to use color matching the site theme.
Round 2 of PR #222 😁
=> Tune PNG rendering - Round 2.

tab_bestpractices.md, tab_headers.md, tab_technical.md
Hi,
This PR performs the following updates: 
* **Response Headers** + **Best Practices** sections:
* Update information about the header `Permissions-Policy`.
* **Technical Resources**  section:
* Add a library for Swift .
* Add the GitHub repository instead of the website for the library **NWebsec** to allow the monitoring of the repository in terms of maintenance.
* Removed the RUST library **owasp-headers** because it was unmaintained since more than 3 years.
* Removed the **Mozilla Observatory** references because related GH repositories were moved to **archived**.
* Added new tools from Mozilla **mdn-http-observatory** replacing the **Mozilla Observatory**.
=> Several updates.

.github/workflows/check-external-links.yml, .github/workflows/headers-generate-json-files.yml, .github/workflows/monitoring-oshp-site-references.yml, .github/workflows/monitoring-technical-references-generate-dashboard.yml, .github/workflows/tab-stats-headers-generate-related-files.yml
Hi,
This PR harden the permissions given to the **GITHUB_TOKEN** by default in all the GitHub workflows.
Set access by default to **read**.
Sources used:
* https://docs.github.com/en/actions/security-for-github-actions/security-guides/automatic-token-authentication#permissions-for-the-github_token
* https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/controlling-permissions-for-github_token
=> Add default permissions to read.

ci/headers_add.json, ci/headers_remove.json, monitoring_technical_references_dashboard.md, tab_bestpractices.md, tab_codesnippets.md, tab_headers.md
> [!WARNING]
> @righettod : Take a first look at the PR.
> [!IMPORTANT]
> Describe the changes performed by the PR.
Hi, Mr.Righetto.
As I asked you via [Blueksy](https://bsky.app/profile/obzva.bsky.social/post/3ln45fgqy2224), it sounds good to update info about CSP header.
I removed the `block-all-mixed-content` directive from `Best Practices` tab and `Code Snippets` tab.
Also I added text `*(Deprecated)*` in `Response Headers` tab.
I ran CI for JSON but I am not sure about I did it right.
Please take a look.
=> Update info about Content-Security-Policy header (Deleting block-all-mixed-content directive)

.github/workflows/monitoring-oshp-site-references.yml, .github/workflows/monitoring-technical-references-generate-dashboard.yml, ci/headers_generate_json_files.py, ci/monitoring_oshp_site_references.py, ci/monitoring_technical_references_generate_dashboard.py, monitoring_technical_references_dashboard.md, tab_casestudies.md
Hi,
This PR:
* Fix a deprecation warning in python scripts.
* Enhance the behavior of the monitoring scripts.
* Update the references into the **Case Studies** tab.
=> Several enhancements.

ci/monitoring_oshp_site_references.py
Hi,
This PR try to fix the error raised by the CI workflow intended to check references to OSHP.
=> Fune error handling

ci/headers_add.json, ci/headers_generate_json_files.py, ci/headers_remove.json
=> Fix build error

tab_bestpractices.md, tab_browsersupport.md, tab_headers.md
Hi,
This PR do the following updates:
* Add new directives for the **Clear-Site-Data** header.
* Add the **X-DNS-Prefetch-Control** header.
* Fix some typos.
Feel free to indicate me if I have missed some elements or made some mistake on some information 😃 
=> Add header X-DNS-Prefetch-Control + other stuff

tab_casestudies.md, tab_headers.md
Hi,
This PR update the ref link to fix this error:
And also remove a dead links.
=> Fix broken ref.
